version: '3.8'

services:
  postgis:
    image: postgis/postgis:17-3.4
    container_name: postgis
    environment:
      POSTGRES_DB: fleetmanBD
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres_network
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: adminer_web
    ports:
      - "8082:8080"
    depends_on:
      - postgis
    networks:
      - postgres_network

volumes:
  postgis_data:

networks:
  postgres_network: